package Frame;

import javax.swing.*;
import java.awt.*;
import java.sql.*;
import Connection.*;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

public class MenuUtama extends javax.swing.JFrame {

    /** Creates new form MenuUtama */
    public MenuUtama() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        waktu();
        try
        {
            int kodee = 0;

            Koneksi objkoneksi = new Koneksi();
            Connection con =objkoneksi.bukakoneksi();
            Statement st = con.createStatement();
            String SQL = "select kode from enabled";
            ResultSet RS=st.executeQuery(SQL);
            while(RS.next())
                {
                    kodee=RS.getInt(1);
                }
           if (kodee==11)
                {
                    menusiswa.setEnabled(false);
                    menumapel.setEnabled(false);
                    menunilai.setEnabled(false);
                    menuguru.setEnabled(false);
                    menureport.setEnabled(true);
                    menusetting.setEnabled(true);
                    subuser.setEnabled(false);
                    sublog.setEnabled(true);
                    subclose.setEnabled(true);
                }
          else if(kodee==12)
                {
                    menusiswa.setEnabled(false);
                    menumapel.setEnabled(false);
                    menunilai.setEnabled(true);
                    menuguru.setEnabled(false);
                    menureport.setEnabled(true);
                    menusetting.setEnabled(true);
                    subuser.setEnabled(false);
                    sublog.setEnabled(true);
                    subclose.setEnabled(true);
                }
          else if(kodee==13)
                {
                    menusiswa.setEnabled(true);
                    menumapel.setEnabled(true);
                    menunilai.setEnabled(true);
                    menuguru.setEnabled(true);
                    menureport.setEnabled(true);
                    menusetting.setEnabled(true);
                    subuser.setEnabled(true);
                    sublog.setEnabled(true);
                    subclose.setEnabled(true);
                }
        }
        catch (SQLException e){}
    }

    void waktu ()
    {
        try
        {
            Waktu objwaktu = new Waktu();
            //System.out.println ( "bisa mengambil waktu ");
            tanggal.setText(objwaktu.getWaktu());
        }
        catch (Exception e)
        {
            System.out.println ("Gagal ambil waktu"+e);
        }
    }

    void hapus()
    {
        try {
            Koneksi objkoneksi = new Koneksi();
            Connection con =objkoneksi.bukakoneksi();
            Statement st = con.createStatement();

            String SQLhapus = "delete from enabled";

            st.executeUpdate(SQLhapus);
            st.close();
            con.close();

        }
    catch(Exception exc){
            System.err.println(exc.getMessage());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menusiswa = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        menumapel = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        menunilai = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuguru = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        menureport = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem15 = new javax.swing.JMenuItem();
        menusetting = new javax.swing.JMenu();
        subuser = new javax.swing.JMenuItem();
        sublog = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        subclose = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SISTEM INFORMASI AKADEMIK");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        tanggal.setText("Tanggal");

        menusiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Medium 044.png"))); // NOI18N
        menusiswa.setText("Data Siswa");

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Addnew toolbar.png"))); // NOI18N
        jMenuItem10.setText("Tambah");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        menusiswa.add(jMenuItem10);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Edit toolbar.png"))); // NOI18N
        jMenuItem11.setText("Edit");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        menusiswa.add(jMenuItem11);

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Delete toolbar.png"))); // NOI18N
        jMenuItem12.setText("Hapus");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        menusiswa.add(jMenuItem12);

        jMenuBar1.add(menusiswa);

        menumapel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Medium 339.png"))); // NOI18N
        menumapel.setText("Mata Pelajaran");

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Addnew toolbar.png"))); // NOI18N
        jMenuItem7.setText("Tambah");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        menumapel.add(jMenuItem7);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Edit toolbar.png"))); // NOI18N
        jMenuItem8.setText("Edit");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        menumapel.add(jMenuItem8);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Delete toolbar.png"))); // NOI18N
        jMenuItem9.setText("Hapus");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        menumapel.add(jMenuItem9);

        jMenuBar1.add(menumapel);

        menunilai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Medium 253.png"))); // NOI18N
        menunilai.setText("Nilai");
        menunilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menunilaiActionPerformed(evt);
            }
        });

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Addnew toolbar.png"))); // NOI18N
        jMenuItem1.setText("Tambah Nilai");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menunilai.add(jMenuItem1);

        jMenuBar1.add(menunilai);

        menuguru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Medium 161.png"))); // NOI18N
        menuguru.setText("Data Guru");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Addnew toolbar.png"))); // NOI18N
        jMenuItem4.setText("Tambah");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuguru.add(jMenuItem4);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Edit toolbar.png"))); // NOI18N
        jMenuItem5.setText("Edit");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menuguru.add(jMenuItem5);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Delete toolbar.png"))); // NOI18N
        jMenuItem6.setText("Hapus");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menuguru.add(jMenuItem6);

        jMenuBar1.add(menuguru);

        menureport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Medium 003.png"))); // NOI18N
        menureport.setText("Report");

        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/viewreport toolbar.png"))); // NOI18N
        jMenuItem13.setText("Siswa");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        menureport.add(jMenuItem13);

        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/viewreport toolbar.png"))); // NOI18N
        jMenuItem14.setText("Guru");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        menureport.add(jMenuItem14);
        menureport.add(jSeparator2);
        menureport.add(jSeparator3);

        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Finddata toolbar.png"))); // NOI18N
        jMenuItem15.setText("Nilai");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        menureport.add(jMenuItem15);

        jMenuBar1.add(menureport);

        menusetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Medium 228.png"))); // NOI18N
        menusetting.setText("Setting");

        subuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/anggota.png"))); // NOI18N
        subuser.setText("User");
        subuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subuserActionPerformed(evt);
            }
        });
        menusetting.add(subuser);

        sublog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        sublog.setText("Log Out");
        sublog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sublogActionPerformed(evt);
            }
        });
        menusetting.add(sublog);
        menusetting.add(jSeparator1);

        subclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Exit.png"))); // NOI18N
        subclose.setText("Close");
        subclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subcloseActionPerformed(evt);
            }
        });
        menusetting.add(subclose);

        jMenuBar1.add(menusetting);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tanggal)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subuserActionPerformed
        //dispose();
        new Setting().setVisible(true);
    }//GEN-LAST:event_subuserActionPerformed

    private void sublogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sublogActionPerformed
        //dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_sublogActionPerformed

    private void subcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subcloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_subcloseActionPerformed

    private void menunilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menunilaiActionPerformed
        
    }//GEN-LAST:event_menunilaiActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        hapus();
        try
        {
            Koneksi objkoneksi = new Koneksi();
            Connection con =objkoneksi.bukakoneksi();
            Statement st = con.createStatement();
            String SQL = "insert into enabled set ket='addsiswa', kode ='1'";
            st.executeUpdate(SQL);
        }
        catch (SQLException e)
        {}

        dispose();
        new DataSiswa().setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        hapus();
        try
        {
            Koneksi objkoneksi = new Koneksi();
            Connection con =objkoneksi.bukakoneksi();
            Statement st = con.createStatement();
            String SQL = "insert into enabled set ket='editsiswa', kode ='7'";
            st.executeUpdate(SQL);
        }
        catch (SQLException e)
        {}

        //dispose();
        new DataSiswa().setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        hapus();
        try
        {
            Koneksi objkoneksi = new Koneksi();
            Connection con =objkoneksi.bukakoneksi();
            Statement st = con.createStatement();
            String SQL = "insert into enabled set ket='delsiswa', kode ='6'";
            st.executeUpdate(SQL);
        }
        catch (SQLException e)
        {}

        //dispose();
        new DataSiswa().setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        hapus();
        try
        {
            Koneksi objkoneksi = new Koneksi();
            Connection con =objkoneksi.bukakoneksi();
            Statement st = con.createStatement();
            String SQL = "insert into enabled set ket='tambahajar', kode ='3'";
            st.executeUpdate(SQL);
        }
        catch (SQLException e)
        {}

        //dispose();
        new DaftarPelajaran().setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        hapus();
        try
        {
            Koneksi objkoneksi = new Koneksi();
            Connection con =objkoneksi.bukakoneksi();
            Statement st = con.createStatement();
            String SQL = "insert into enabled set ket='editajar', kode ='9'";
            st.executeUpdate(SQL);
        }
        catch (SQLException e)
        {}

        //dispose();
        new DaftarPelajaran().setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        hapus();
        try
        {
            Koneksi objkoneksi = new Koneksi();
            Connection con =objkoneksi.bukakoneksi();
            Statement st = con.createStatement();
            String SQL = "insert into enabled set ket='hapusajar', kode ='10'";
            st.executeUpdate(SQL);
        }
        catch (SQLException e)
        {}

        //dispose();
        new DaftarPelajaran().setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        hapus();
        try
        {
            Koneksi objkoneksi = new Koneksi();
            Connection con =objkoneksi.bukakoneksi();
            Statement st = con.createStatement();
            String SQL = "insert into enabled set ket='addguru', kode ='2'";
            st.executeUpdate(SQL);
        }
        catch (SQLException e)
        {}
        //dispose();
        new DataGuru().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        hapus();
        try
        {
            Koneksi objkoneksi = new Koneksi();
            Connection con =objkoneksi.bukakoneksi();
            Statement st = con.createStatement();
            String SQL = "insert into enabled set ket='delguru', kode ='5'";
            st.executeUpdate(SQL);
        }
        catch (SQLException e)
        {}
        //dispose();
        new DataGuru().setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        hapus();
        try
        {
            Koneksi objkoneksi = new Koneksi();
            Connection con =objkoneksi.bukakoneksi();
            Statement st = con.createStatement();
            String SQL = "insert into enabled set ket='editguru', kode ='8'";
            st.executeUpdate(SQL);
        }
        catch (SQLException e)
        {}
        //dispose();
        new DataGuru().setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        try{
            Koneksi objkoneksi = new Koneksi();
            Connection con =objkoneksi.bukakoneksi();
            String fileName="C:/Users/Anonymous/Downloads/Compressed/SIA/UPK/UKK/src/report/DaftarNilai.jrxml";
            String filetoFill="C:/Users/Anonymous/Downloads/Compressed/SIA/UPK/UKK/src/report/DaftarNilai.jasper";
            JasperCompileManager.compileReport(fileName);
            Map param= new HashMap();
            JasperFillManager.fillReport(filetoFill, param, con);
            JasperPrint jp=JasperFillManager.fillReport(filetoFill, param,con);
            JasperViewer.viewReport(jp,false);

        }catch(Exception ex){
               System.out.println(ex.toString());
        }
        //new CariDataSiswa().setVisible(true);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //dispose();
        new Nilai().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        try{
            Koneksi objkoneksi = new Koneksi();
            Connection con =objkoneksi.bukakoneksi();
            String fileName="C:/Users/Anonymous/Downloads/Compressed/SIA/UPK/UKK/src/report/DaftarSiswa.jrxml";
            String filetoFill="C:/Users/Anonymous/Downloads/Compressed/SIA/UPK/UKK/src/report/DaftarSiswa.jasper";
            JasperCompileManager.compileReport(fileName);
            Map param= new HashMap();
            JasperFillManager.fillReport(filetoFill, param, con);
            JasperPrint jp=JasperFillManager.fillReport(filetoFill, param,con);
            JasperViewer.viewReport(jp,false);

        }catch(Exception ex){
               System.out.println(ex.toString());
        }
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        try{
            Koneksi objkoneksi = new Koneksi();
            Connection con =objkoneksi.bukakoneksi();
            String fileName="C:/Users/Anonymous/Downloads/Compressed/SIA/UPK/UKK/src/report/DaftarGuru.jrxml";
            String filetoFill="C:/Users/Anonymous/Downloads/Compressed/SIA/UPK/UKK/src/report/DaftarGuru.jasper";
            JasperCompileManager.compileReport(fileName);
            Map param= new HashMap();
            JasperFillManager.fillReport(filetoFill, param, con);
            JasperPrint jp=JasperFillManager.fillReport(filetoFill, param,con);
            JasperViewer.viewReport(jp,false);

        }catch(Exception ex){
               System.out.println(ex.toString());
        }
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenu menuguru;
    private javax.swing.JMenu menumapel;
    private javax.swing.JMenu menunilai;
    private javax.swing.JMenu menureport;
    private javax.swing.JMenu menusetting;
    private javax.swing.JMenu menusiswa;
    private javax.swing.JMenuItem subclose;
    private javax.swing.JMenuItem sublog;
    private javax.swing.JMenuItem subuser;
    private javax.swing.JLabel tanggal;
    // End of variables declaration//GEN-END:variables

}
